/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package WIN33CLC_VIEW;

/**
 *
 * @author LuFraVaPe
 */
public class ayuda extends javax.swing.JPanel {

    /**
     * Creates new form ayuda
     */
    public ayuda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu_salir3 = new RSMaterialComponent.RSPanelMaterial();
        jLabel9 = new javax.swing.JLabel();
        rSDateChooser1 = new rojerusan.RSDateChooser();
        btn_horario_disponible = new RSMaterialComponent.RSButtonMaterialGradientOne();
        rSRadioButtonMaterial1 = new RSMaterialComponent.RSRadioButtonMaterial();
        rSRadioButtonMaterial2 = new RSMaterialComponent.RSRadioButtonMaterial();
        rSRadioButtonMaterial3 = new RSMaterialComponent.RSRadioButtonMaterial();
        rSRadioButtonMaterial4 = new RSMaterialComponent.RSRadioButtonMaterial();
        rSRadioButtonMaterial5 = new RSMaterialComponent.RSRadioButtonMaterial();
        rSRadioButtonMaterial6 = new RSMaterialComponent.RSRadioButtonMaterial();
        rSRadioButtonMaterial7 = new RSMaterialComponent.RSRadioButtonMaterial();
        rSRadioButtonMaterial8 = new RSMaterialComponent.RSRadioButtonMaterial();
        rSRadioButtonMaterial9 = new RSMaterialComponent.RSRadioButtonMaterial();
        rSRadioButtonMaterial10 = new RSMaterialComponent.RSRadioButtonMaterial();
        rSRadioButtonMaterial11 = new RSMaterialComponent.RSRadioButtonMaterial();
        rSRadioButtonMaterial12 = new RSMaterialComponent.RSRadioButtonMaterial();
        rSRadioButtonMaterial13 = new RSMaterialComponent.RSRadioButtonMaterial();
        rSRadioButtonMaterial14 = new RSMaterialComponent.RSRadioButtonMaterial();
        menu_salir2 = new RSMaterialComponent.RSPanelMaterial();
        menu_salir5 = new RSMaterialComponent.RSPanelMaterial();
        txt_dni1 = new rojerusan.RSMetroTextPlaceHolder();
        jLabel16 = new javax.swing.JLabel();
        btn_buscar_reniec1 = new RSMaterialComponent.RSButtonMaterialGradientOne();
        fSTexFieldMD1 = new LIB.FSTexFieldMD();

        menu_salir3.setBackground(new java.awt.Color(255, 255, 255));
        menu_salir3.setBgShade(new java.awt.Color(204, 204, 204));
        menu_salir3.setPreferredSize(new java.awt.Dimension(90, 62));
        menu_salir3.setRound(40);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("FECHA DE LA CITA:");

        rSDateChooser1.setColorBackground(new java.awt.Color(23, 144, 244));
        rSDateChooser1.setColorButtonHover(new java.awt.Color(23, 144, 244));
        rSDateChooser1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rSDateChooser1.setFormatoFecha("dd/MM/yyyy");
        rSDateChooser1.setFuente(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btn_horario_disponible.setForeground(new java.awt.Color(51, 51, 51));
        btn_horario_disponible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WIN34CLC_RESOURCES_UI/icons8-buscar-en-la-lista-24.png"))); // NOI18N
        btn_horario_disponible.setText("Ver horario disponible");
        btn_horario_disponible.setBorderPainted(false);
        btn_horario_disponible.setColorPrimario(new java.awt.Color(41, 177, 255));
        btn_horario_disponible.setColorPrimarioHover(new java.awt.Color(41, 177, 255));
        btn_horario_disponible.setColorSecundario(new java.awt.Color(41, 177, 255));
        btn_horario_disponible.setColorSecundarioHover(new java.awt.Color(41, 177, 255));
        btn_horario_disponible.setFocusPainted(false);
        btn_horario_disponible.setFont(new java.awt.Font("Segoe UI Black", 0, 15)); // NOI18N

        rSRadioButtonMaterial1.setForeground(new java.awt.Color(51, 51, 51));
        rSRadioButtonMaterial1.setText("8:00 - 8:30");
        rSRadioButtonMaterial1.setColorCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial1.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial1.setFocusPainted(false);
        rSRadioButtonMaterial1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rSRadioButtonMaterial1.setRippleColor(new java.awt.Color(0, 112, 192));

        rSRadioButtonMaterial2.setForeground(new java.awt.Color(51, 51, 51));
        rSRadioButtonMaterial2.setText("8:30 - 9:00");
        rSRadioButtonMaterial2.setColorCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial2.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial2.setFocusPainted(false);
        rSRadioButtonMaterial2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rSRadioButtonMaterial2.setRippleColor(new java.awt.Color(0, 112, 192));

        rSRadioButtonMaterial3.setForeground(new java.awt.Color(51, 51, 51));
        rSRadioButtonMaterial3.setText("9:00 - 9:30");
        rSRadioButtonMaterial3.setColorCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial3.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial3.setFocusPainted(false);
        rSRadioButtonMaterial3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rSRadioButtonMaterial3.setRippleColor(new java.awt.Color(0, 112, 192));

        rSRadioButtonMaterial4.setForeground(new java.awt.Color(51, 51, 51));
        rSRadioButtonMaterial4.setText("9:30 - 10:00");
        rSRadioButtonMaterial4.setColorCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial4.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial4.setFocusPainted(false);
        rSRadioButtonMaterial4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rSRadioButtonMaterial4.setRippleColor(new java.awt.Color(0, 112, 192));

        rSRadioButtonMaterial5.setForeground(new java.awt.Color(51, 51, 51));
        rSRadioButtonMaterial5.setText("10:00 - 10:30");
        rSRadioButtonMaterial5.setColorCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial5.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial5.setFocusPainted(false);
        rSRadioButtonMaterial5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rSRadioButtonMaterial5.setRippleColor(new java.awt.Color(0, 112, 192));

        rSRadioButtonMaterial6.setForeground(new java.awt.Color(51, 51, 51));
        rSRadioButtonMaterial6.setText("10:30 - 11:00");
        rSRadioButtonMaterial6.setColorCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial6.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial6.setFocusPainted(false);
        rSRadioButtonMaterial6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rSRadioButtonMaterial6.setRippleColor(new java.awt.Color(0, 112, 192));

        rSRadioButtonMaterial7.setForeground(new java.awt.Color(51, 51, 51));
        rSRadioButtonMaterial7.setText("11:00 - 11:30");
        rSRadioButtonMaterial7.setColorCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial7.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial7.setFocusPainted(false);
        rSRadioButtonMaterial7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rSRadioButtonMaterial7.setRippleColor(new java.awt.Color(0, 112, 192));

        rSRadioButtonMaterial8.setForeground(new java.awt.Color(51, 51, 51));
        rSRadioButtonMaterial8.setText("11:30 - 12:00");
        rSRadioButtonMaterial8.setColorCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial8.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial8.setFocusPainted(false);
        rSRadioButtonMaterial8.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rSRadioButtonMaterial8.setRippleColor(new java.awt.Color(0, 112, 192));

        rSRadioButtonMaterial9.setForeground(new java.awt.Color(51, 51, 51));
        rSRadioButtonMaterial9.setText("12:00 - 12:30");
        rSRadioButtonMaterial9.setColorCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial9.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial9.setFocusPainted(false);
        rSRadioButtonMaterial9.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rSRadioButtonMaterial9.setRippleColor(new java.awt.Color(0, 112, 192));

        rSRadioButtonMaterial10.setForeground(new java.awt.Color(51, 51, 51));
        rSRadioButtonMaterial10.setText("12:30 - 13:00");
        rSRadioButtonMaterial10.setColorCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial10.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial10.setFocusPainted(false);
        rSRadioButtonMaterial10.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rSRadioButtonMaterial10.setRippleColor(new java.awt.Color(0, 112, 192));

        rSRadioButtonMaterial11.setForeground(new java.awt.Color(51, 51, 51));
        rSRadioButtonMaterial11.setText("13:00 - 13:30");
        rSRadioButtonMaterial11.setColorCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial11.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial11.setFocusPainted(false);
        rSRadioButtonMaterial11.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rSRadioButtonMaterial11.setRippleColor(new java.awt.Color(0, 112, 192));

        rSRadioButtonMaterial12.setForeground(new java.awt.Color(51, 51, 51));
        rSRadioButtonMaterial12.setText("13:30 - 14:00");
        rSRadioButtonMaterial12.setColorCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial12.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial12.setFocusPainted(false);
        rSRadioButtonMaterial12.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rSRadioButtonMaterial12.setRippleColor(new java.awt.Color(0, 112, 192));

        rSRadioButtonMaterial13.setForeground(new java.awt.Color(51, 51, 51));
        rSRadioButtonMaterial13.setText("14:00 - 14:30");
        rSRadioButtonMaterial13.setColorCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial13.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial13.setFocusPainted(false);
        rSRadioButtonMaterial13.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rSRadioButtonMaterial13.setRippleColor(new java.awt.Color(0, 112, 192));

        rSRadioButtonMaterial14.setForeground(new java.awt.Color(51, 51, 51));
        rSRadioButtonMaterial14.setText("14:30 - 15:00");
        rSRadioButtonMaterial14.setColorCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial14.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial14.setFocusPainted(false);
        rSRadioButtonMaterial14.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rSRadioButtonMaterial14.setRippleColor(new java.awt.Color(0, 112, 192));

        javax.swing.GroupLayout menu_salir3Layout = new javax.swing.GroupLayout(menu_salir3);
        menu_salir3.setLayout(menu_salir3Layout);
        menu_salir3Layout.setHorizontalGroup(
            menu_salir3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_salir3Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(menu_salir3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addGroup(menu_salir3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(menu_salir3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rSRadioButtonMaterial9, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(rSRadioButtonMaterial5, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(rSRadioButtonMaterial13, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(rSRadioButtonMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addGroup(menu_salir3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menu_salir3Layout.createSequentialGroup()
                        .addGap(18, 25, Short.MAX_VALUE)
                        .addComponent(rSDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(btn_horario_disponible, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                        .addContainerGap(48, Short.MAX_VALUE))
                    .addGroup(menu_salir3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(menu_salir3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rSRadioButtonMaterial6, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(rSRadioButtonMaterial10, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(rSRadioButtonMaterial2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(rSRadioButtonMaterial14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(menu_salir3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rSRadioButtonMaterial3, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(rSRadioButtonMaterial7, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(rSRadioButtonMaterial11, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(menu_salir3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rSRadioButtonMaterial8, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(rSRadioButtonMaterial4, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(rSRadioButtonMaterial12, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        menu_salir3Layout.setVerticalGroup(
            menu_salir3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_salir3Layout.createSequentialGroup()
                .addGroup(menu_salir3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menu_salir3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(menu_salir3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_horario_disponible, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rSDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(menu_salir3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addGroup(menu_salir3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSRadioButtonMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSRadioButtonMaterial2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSRadioButtonMaterial3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSRadioButtonMaterial4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(menu_salir3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSRadioButtonMaterial5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSRadioButtonMaterial6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSRadioButtonMaterial7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSRadioButtonMaterial8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(menu_salir3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSRadioButtonMaterial9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSRadioButtonMaterial10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSRadioButtonMaterial11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSRadioButtonMaterial12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(menu_salir3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSRadioButtonMaterial13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSRadioButtonMaterial14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        menu_salir2.setBackground(new java.awt.Color(255, 255, 255));
        menu_salir2.setBgShade(new java.awt.Color(204, 204, 204));
        menu_salir2.setPreferredSize(new java.awt.Dimension(90, 62));
        menu_salir2.setRound(40);

        javax.swing.GroupLayout menu_salir2Layout = new javax.swing.GroupLayout(menu_salir2);
        menu_salir2.setLayout(menu_salir2Layout);
        menu_salir2Layout.setHorizontalGroup(
            menu_salir2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );
        menu_salir2Layout.setVerticalGroup(
            menu_salir2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 104, Short.MAX_VALUE)
        );

        menu_salir5.setBackground(new java.awt.Color(255, 255, 255));
        menu_salir5.setBgShade(new java.awt.Color(204, 204, 204));
        menu_salir5.setPreferredSize(new java.awt.Dimension(90, 62));
        menu_salir5.setRound(40);

        txt_dni1.setForeground(new java.awt.Color(51, 51, 51));
        txt_dni1.setBorderColor(new java.awt.Color(153, 153, 153));
        txt_dni1.setBotonColor(new java.awt.Color(3, 111, 198));
        txt_dni1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("DNI:");

        btn_buscar_reniec1.setForeground(new java.awt.Color(51, 51, 51));
        btn_buscar_reniec1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WIN34CLC_RESOURCES_UI/icons8-encuentra-hombre-usuario-24.png"))); // NOI18N
        btn_buscar_reniec1.setText("Buscar en Reniec");
        btn_buscar_reniec1.setBorderPainted(false);
        btn_buscar_reniec1.setColorPrimario(new java.awt.Color(41, 177, 255));
        btn_buscar_reniec1.setColorPrimarioHover(new java.awt.Color(41, 177, 255));
        btn_buscar_reniec1.setColorSecundario(new java.awt.Color(41, 177, 255));
        btn_buscar_reniec1.setColorSecundarioHover(new java.awt.Color(41, 177, 255));
        btn_buscar_reniec1.setFocusPainted(false);
        btn_buscar_reniec1.setFont(new java.awt.Font("Segoe UI Black", 0, 15)); // NOI18N

        javax.swing.GroupLayout menu_salir5Layout = new javax.swing.GroupLayout(menu_salir5);
        menu_salir5.setLayout(menu_salir5Layout);
        menu_salir5Layout.setHorizontalGroup(
            menu_salir5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_salir5Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_dni1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addGap(84, 84, 84)
                .addComponent(btn_buscar_reniec1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228))
        );
        menu_salir5Layout.setVerticalGroup(
            menu_salir5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_salir5Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(menu_salir5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txt_dni1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar_reniec1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        fSTexFieldMD1.setForeground(new java.awt.Color(51, 51, 51));
        fSTexFieldMD1.setBordeColorFocus(new java.awt.Color(0, 112, 192));
        fSTexFieldMD1.setCaretColor(new java.awt.Color(51, 51, 51));
        fSTexFieldMD1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fSTexFieldMD1.setPlaceholder("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu_salir3, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menu_salir2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(fSTexFieldMD1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(menu_salir5, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menu_salir2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(fSTexFieldMD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)))
                .addComponent(menu_salir5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(menu_salir3, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialGradientOne btn_buscar_reniec1;
    private RSMaterialComponent.RSButtonMaterialGradientOne btn_horario_disponible;
    private LIB.FSTexFieldMD fSTexFieldMD1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel9;
    private RSMaterialComponent.RSPanelMaterial menu_salir2;
    private RSMaterialComponent.RSPanelMaterial menu_salir3;
    private RSMaterialComponent.RSPanelMaterial menu_salir5;
    private rojerusan.RSDateChooser rSDateChooser1;
    private RSMaterialComponent.RSRadioButtonMaterial rSRadioButtonMaterial1;
    private RSMaterialComponent.RSRadioButtonMaterial rSRadioButtonMaterial10;
    private RSMaterialComponent.RSRadioButtonMaterial rSRadioButtonMaterial11;
    private RSMaterialComponent.RSRadioButtonMaterial rSRadioButtonMaterial12;
    private RSMaterialComponent.RSRadioButtonMaterial rSRadioButtonMaterial13;
    private RSMaterialComponent.RSRadioButtonMaterial rSRadioButtonMaterial14;
    private RSMaterialComponent.RSRadioButtonMaterial rSRadioButtonMaterial2;
    private RSMaterialComponent.RSRadioButtonMaterial rSRadioButtonMaterial3;
    private RSMaterialComponent.RSRadioButtonMaterial rSRadioButtonMaterial4;
    private RSMaterialComponent.RSRadioButtonMaterial rSRadioButtonMaterial5;
    private RSMaterialComponent.RSRadioButtonMaterial rSRadioButtonMaterial6;
    private RSMaterialComponent.RSRadioButtonMaterial rSRadioButtonMaterial7;
    private RSMaterialComponent.RSRadioButtonMaterial rSRadioButtonMaterial8;
    private RSMaterialComponent.RSRadioButtonMaterial rSRadioButtonMaterial9;
    private rojerusan.RSMetroTextPlaceHolder txt_dni1;
    // End of variables declaration//GEN-END:variables
}
