/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package WIN33CLC_VIEW;

import WIN30CLC_DAO.DaoException;
import WIN32CLC_CTR.CTR_05_Citas;
import WIN32CLC_CTR.CTR_11_DataBaseConfiguration;
import WIN35CLC_REPORTS.CLASS.Rpt_Patients;
import WIN_2020_UTILS.ConfigReader;
import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Cesar
 */
public class test_para_lanzar_metodos extends javax.swing.JFrame {

    /**
     * Creates new form test_para_lanzar_metodos
     */
    public test_para_lanzar_metodos() {
        initComponents();
        
        
        
        
 
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        rSRadioButtonMaterial29 = new RSMaterialComponent.RSRadioButtonMaterial();
        rSRadioButtonMaterial30 = new RSMaterialComponent.RSRadioButtonMaterial();
        rSRadioButtonMaterial31 = new RSMaterialComponent.RSRadioButtonMaterial();
        rSRadioButtonMaterial32 = new RSMaterialComponent.RSRadioButtonMaterial();
        rSRadioButtonMaterial33 = new RSMaterialComponent.RSRadioButtonMaterial();
        rSRadioButtonMaterial34 = new RSMaterialComponent.RSRadioButtonMaterial();
        rSRadioButtonMaterial35 = new RSMaterialComponent.RSRadioButtonMaterial();
        rSRadioButtonMaterial36 = new RSMaterialComponent.RSRadioButtonMaterial();
        rSRadioButtonMaterial37 = new RSMaterialComponent.RSRadioButtonMaterial();
        rSRadioButtonMaterial38 = new RSMaterialComponent.RSRadioButtonMaterial();
        rSRadioButtonMaterial39 = new RSMaterialComponent.RSRadioButtonMaterial();
        rSRadioButtonMaterial41 = new RSMaterialComponent.RSRadioButtonMaterial();
        rSRadioButtonMaterial42 = new RSMaterialComponent.RSRadioButtonMaterial();
        rSRadioButtonMaterial43 = new RSMaterialComponent.RSRadioButtonMaterial();
        jPanel3 = new javax.swing.JPanel();
        rbx_1 = new RSMaterialComponent.RSRadioButtonMaterial();
        rbx_5 = new RSMaterialComponent.RSRadioButtonMaterial();
        rbx_9 = new RSMaterialComponent.RSRadioButtonMaterial();
        rbx_13 = new RSMaterialComponent.RSRadioButtonMaterial();
        rbx_2 = new RSMaterialComponent.RSRadioButtonMaterial();
        rbx_6 = new RSMaterialComponent.RSRadioButtonMaterial();
        rbx_10 = new RSMaterialComponent.RSRadioButtonMaterial();
        rbx_14 = new RSMaterialComponent.RSRadioButtonMaterial();
        rbx_3 = new RSMaterialComponent.RSRadioButtonMaterial();
        rbx_7 = new RSMaterialComponent.RSRadioButtonMaterial();
        rbx_11 = new RSMaterialComponent.RSRadioButtonMaterial();
        rbx_4 = new RSMaterialComponent.RSRadioButtonMaterial();
        rbx_8 = new RSMaterialComponent.RSRadioButtonMaterial();
        rbx_12 = new RSMaterialComponent.RSRadioButtonMaterial();
        jPanel4 = new javax.swing.JPanel();
        rSDateChooser2 = new rojeru_san.componentes.RSDateChooser();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("crear backup");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("restorebackup");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("clear databse");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        rSRadioButtonMaterial29.setForeground(new java.awt.Color(51, 51, 51));
        rSRadioButtonMaterial29.setText("8:00 - 8:30");
        rSRadioButtonMaterial29.setColorCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial29.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial29.setFocusPainted(false);
        rSRadioButtonMaterial29.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rSRadioButtonMaterial29.setRippleColor(new java.awt.Color(0, 112, 192));

        rSRadioButtonMaterial30.setForeground(new java.awt.Color(51, 51, 51));
        rSRadioButtonMaterial30.setText("10:00 - 10:30");
        rSRadioButtonMaterial30.setColorCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial30.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial30.setFocusPainted(false);
        rSRadioButtonMaterial30.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rSRadioButtonMaterial30.setRippleColor(new java.awt.Color(0, 112, 192));

        rSRadioButtonMaterial31.setForeground(new java.awt.Color(51, 51, 51));
        rSRadioButtonMaterial31.setText("12:00 - 12:30");
        rSRadioButtonMaterial31.setColorCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial31.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial31.setFocusPainted(false);
        rSRadioButtonMaterial31.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rSRadioButtonMaterial31.setRippleColor(new java.awt.Color(0, 112, 192));

        rSRadioButtonMaterial32.setForeground(new java.awt.Color(51, 51, 51));
        rSRadioButtonMaterial32.setText("14:00 - 14:30");
        rSRadioButtonMaterial32.setColorCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial32.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial32.setFocusPainted(false);
        rSRadioButtonMaterial32.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rSRadioButtonMaterial32.setRippleColor(new java.awt.Color(0, 112, 192));

        rSRadioButtonMaterial33.setForeground(new java.awt.Color(51, 51, 51));
        rSRadioButtonMaterial33.setText("8:30 - 9:00");
        rSRadioButtonMaterial33.setColorCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial33.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial33.setFocusPainted(false);
        rSRadioButtonMaterial33.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rSRadioButtonMaterial33.setRippleColor(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSRadioButtonMaterial33ActionPerformed(evt);
            }
        });

        rSRadioButtonMaterial34.setForeground(new java.awt.Color(51, 51, 51));
        rSRadioButtonMaterial34.setText("10:30 - 11:00");
        rSRadioButtonMaterial34.setColorCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial34.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial34.setFocusPainted(false);
        rSRadioButtonMaterial34.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rSRadioButtonMaterial34.setRippleColor(new java.awt.Color(0, 112, 192));

        rSRadioButtonMaterial35.setForeground(new java.awt.Color(51, 51, 51));
        rSRadioButtonMaterial35.setText("12:30 - 13:00");
        rSRadioButtonMaterial35.setColorCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial35.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial35.setFocusPainted(false);
        rSRadioButtonMaterial35.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rSRadioButtonMaterial35.setRippleColor(new java.awt.Color(0, 112, 192));

        rSRadioButtonMaterial36.setForeground(new java.awt.Color(51, 51, 51));
        rSRadioButtonMaterial36.setText("14:30 - 15:00");
        rSRadioButtonMaterial36.setColorCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial36.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial36.setFocusPainted(false);
        rSRadioButtonMaterial36.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rSRadioButtonMaterial36.setRippleColor(new java.awt.Color(0, 112, 192));

        rSRadioButtonMaterial37.setForeground(new java.awt.Color(51, 51, 51));
        rSRadioButtonMaterial37.setText("9:00 - 9:30");
        rSRadioButtonMaterial37.setColorCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial37.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial37.setFocusPainted(false);
        rSRadioButtonMaterial37.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rSRadioButtonMaterial37.setRippleColor(new java.awt.Color(0, 112, 192));

        rSRadioButtonMaterial38.setForeground(new java.awt.Color(51, 51, 51));
        rSRadioButtonMaterial38.setText("11:.00 - 11:30");
        rSRadioButtonMaterial38.setColorCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial38.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial38.setFocusPainted(false);
        rSRadioButtonMaterial38.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rSRadioButtonMaterial38.setRippleColor(new java.awt.Color(0, 112, 192));

        rSRadioButtonMaterial39.setForeground(new java.awt.Color(51, 51, 51));
        rSRadioButtonMaterial39.setText("13:00 - 13:30");
        rSRadioButtonMaterial39.setColorCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial39.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial39.setFocusPainted(false);
        rSRadioButtonMaterial39.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rSRadioButtonMaterial39.setRippleColor(new java.awt.Color(0, 112, 192));

        rSRadioButtonMaterial41.setForeground(new java.awt.Color(51, 51, 51));
        rSRadioButtonMaterial41.setText("9:00 - 9:30");
        rSRadioButtonMaterial41.setColorCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial41.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial41.setFocusPainted(false);
        rSRadioButtonMaterial41.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rSRadioButtonMaterial41.setRippleColor(new java.awt.Color(0, 112, 192));

        rSRadioButtonMaterial42.setForeground(new java.awt.Color(51, 51, 51));
        rSRadioButtonMaterial42.setText("11:.00 - 11:30");
        rSRadioButtonMaterial42.setColorCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial42.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial42.setFocusPainted(false);
        rSRadioButtonMaterial42.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rSRadioButtonMaterial42.setRippleColor(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSRadioButtonMaterial42ActionPerformed(evt);
            }
        });

        rSRadioButtonMaterial43.setForeground(new java.awt.Color(51, 51, 51));
        rSRadioButtonMaterial43.setText("13:00 - 13:30");
        rSRadioButtonMaterial43.setColorCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial43.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rSRadioButtonMaterial43.setFocusPainted(false);
        rSRadioButtonMaterial43.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rSRadioButtonMaterial43.setRippleColor(new java.awt.Color(0, 112, 192));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rSRadioButtonMaterial30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(rSRadioButtonMaterial29, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(rSRadioButtonMaterial32, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(rSRadioButtonMaterial31, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSRadioButtonMaterial33, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(rSRadioButtonMaterial34, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(rSRadioButtonMaterial35, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(rSRadioButtonMaterial36, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSRadioButtonMaterial37, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(rSRadioButtonMaterial38, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(rSRadioButtonMaterial39, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSRadioButtonMaterial41, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(rSRadioButtonMaterial42, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(rSRadioButtonMaterial43, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rSRadioButtonMaterial41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSRadioButtonMaterial37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSRadioButtonMaterial29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSRadioButtonMaterial33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rSRadioButtonMaterial34, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rSRadioButtonMaterial38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rSRadioButtonMaterial42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rSRadioButtonMaterial30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSRadioButtonMaterial35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSRadioButtonMaterial31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSRadioButtonMaterial39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSRadioButtonMaterial43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSRadioButtonMaterial36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSRadioButtonMaterial32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        rbx_1.setForeground(new java.awt.Color(51, 51, 51));
        rbx_1.setText("8:00 - 8:30");
        rbx_1.setColorCheck(new java.awt.Color(0, 112, 192));
        rbx_1.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rbx_1.setFocusPainted(false);
        rbx_1.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        rbx_1.setRippleColor(new java.awt.Color(0, 112, 192));
        rbx_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbx_1ActionPerformed(evt);
            }
        });

        rbx_5.setForeground(new java.awt.Color(51, 51, 51));
        rbx_5.setText("10:00 - 10:30");
        rbx_5.setColorCheck(new java.awt.Color(0, 112, 192));
        rbx_5.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rbx_5.setFocusPainted(false);
        rbx_5.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        rbx_5.setRippleColor(new java.awt.Color(0, 112, 192));

        rbx_9.setForeground(new java.awt.Color(51, 51, 51));
        rbx_9.setText("12:00 - 12:30");
        rbx_9.setColorCheck(new java.awt.Color(0, 112, 192));
        rbx_9.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rbx_9.setFocusPainted(false);
        rbx_9.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        rbx_9.setRippleColor(new java.awt.Color(0, 112, 192));

        rbx_13.setForeground(new java.awt.Color(51, 51, 51));
        rbx_13.setText("14:00 - 14:30");
        rbx_13.setColorCheck(new java.awt.Color(0, 112, 192));
        rbx_13.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rbx_13.setFocusPainted(false);
        rbx_13.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        rbx_13.setRippleColor(new java.awt.Color(0, 112, 192));

        rbx_2.setForeground(new java.awt.Color(51, 51, 51));
        rbx_2.setText("8:30 - 9:00");
        rbx_2.setColorCheck(new java.awt.Color(0, 112, 192));
        rbx_2.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rbx_2.setFocusPainted(false);
        rbx_2.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        rbx_2.setRippleColor(new java.awt.Color(0, 112, 192));
        rbx_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbx_2ActionPerformed(evt);
            }
        });

        rbx_6.setForeground(new java.awt.Color(51, 51, 51));
        rbx_6.setText("10:30 - 11:00");
        rbx_6.setColorCheck(new java.awt.Color(0, 112, 192));
        rbx_6.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rbx_6.setFocusPainted(false);
        rbx_6.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        rbx_6.setRippleColor(new java.awt.Color(0, 112, 192));

        rbx_10.setForeground(new java.awt.Color(51, 51, 51));
        rbx_10.setText("12:30 - 13:00");
        rbx_10.setColorCheck(new java.awt.Color(0, 112, 192));
        rbx_10.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rbx_10.setFocusPainted(false);
        rbx_10.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        rbx_10.setRippleColor(new java.awt.Color(0, 112, 192));

        rbx_14.setForeground(new java.awt.Color(51, 51, 51));
        rbx_14.setText("14:30 - 15:00");
        rbx_14.setColorCheck(new java.awt.Color(0, 112, 192));
        rbx_14.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rbx_14.setFocusPainted(false);
        rbx_14.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        rbx_14.setRippleColor(new java.awt.Color(0, 112, 192));

        rbx_3.setForeground(new java.awt.Color(51, 51, 51));
        rbx_3.setText("9:00 - 9:30");
        rbx_3.setColorCheck(new java.awt.Color(0, 112, 192));
        rbx_3.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rbx_3.setFocusPainted(false);
        rbx_3.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        rbx_3.setRippleColor(new java.awt.Color(0, 112, 192));

        rbx_7.setForeground(new java.awt.Color(51, 51, 51));
        rbx_7.setText("11:.00 - 11:30");
        rbx_7.setColorCheck(new java.awt.Color(0, 112, 192));
        rbx_7.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rbx_7.setFocusPainted(false);
        rbx_7.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        rbx_7.setRippleColor(new java.awt.Color(0, 112, 192));

        rbx_11.setForeground(new java.awt.Color(51, 51, 51));
        rbx_11.setText("13:00 - 13:30");
        rbx_11.setColorCheck(new java.awt.Color(0, 112, 192));
        rbx_11.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rbx_11.setFocusPainted(false);
        rbx_11.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        rbx_11.setRippleColor(new java.awt.Color(0, 112, 192));

        rbx_4.setForeground(new java.awt.Color(51, 51, 51));
        rbx_4.setText("9:00 - 9:30");
        rbx_4.setColorCheck(new java.awt.Color(0, 112, 192));
        rbx_4.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rbx_4.setFocusPainted(false);
        rbx_4.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        rbx_4.setRippleColor(new java.awt.Color(0, 112, 192));

        rbx_8.setForeground(new java.awt.Color(51, 51, 51));
        rbx_8.setText("11:.00 - 11:30");
        rbx_8.setColorCheck(new java.awt.Color(0, 112, 192));
        rbx_8.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rbx_8.setFocusPainted(false);
        rbx_8.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        rbx_8.setRippleColor(new java.awt.Color(0, 112, 192));
        rbx_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbx_8ActionPerformed(evt);
            }
        });

        rbx_12.setForeground(new java.awt.Color(51, 51, 51));
        rbx_12.setText("13:00 - 13:30");
        rbx_12.setColorCheck(new java.awt.Color(0, 112, 192));
        rbx_12.setColorUnCheck(new java.awt.Color(0, 112, 192));
        rbx_12.setFocusPainted(false);
        rbx_12.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        rbx_12.setRippleColor(new java.awt.Color(0, 112, 192));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbx_5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(rbx_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(rbx_13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(rbx_9, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(18, 26, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbx_2, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(rbx_6, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(rbx_10, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(rbx_14, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 26, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbx_3, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(rbx_7, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(rbx_11, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbx_4, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(rbx_8, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(rbx_12, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rbx_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbx_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbx_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbx_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbx_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rbx_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rbx_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rbx_5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbx_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbx_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbx_11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbx_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbx_14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbx_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rSDateChooser2.setColorBackground(new java.awt.Color(3, 111, 198));
        rSDateChooser2.setColorButtonHover(new java.awt.Color(3, 111, 198));
        rSDateChooser2.setColorDiaActual(new java.awt.Color(255, 0, 0));
        rSDateChooser2.setColorForeground(new java.awt.Color(3, 111, 198));
        rSDateChooser2.setFuente(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("FECHA DE LA CITA:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(rSDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap(265, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(rSDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel9)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(47, 47, 47)
                        .addComponent(jButton2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(150, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(86, 86, 86)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(32, 32, 32)
                .addComponent(jButton3)
                .addGap(105, 105, 105)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(351, 351, 351)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(475, 475, 475)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(475, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String path = null, filename;


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        generateBackUpMysql();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        restoreBackUpMysql();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            CTR_11_DataBaseConfiguration baseConfiguration = new CTR_11_DataBaseConfiguration();
            if(baseConfiguration.RESETDATABASE())
                System.out.println("reset success");
            else
                System.out.println("fail restore");
        } catch (SQLException ex) {
            Logger.getLogger(test_para_lanzar_metodos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void rSRadioButtonMaterial33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSRadioButtonMaterial33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSRadioButtonMaterial33ActionPerformed

    private void rSRadioButtonMaterial42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSRadioButtonMaterial42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSRadioButtonMaterial42ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            ConfigReader properties = new ConfigReader();
            System.out.println(properties.getPropValues().getMySqlDAOMANAGER_db_name());
            System.out.println(properties.getPropValues().getMySqlDAOMANAGER_db_pass());
            System.out.println(properties.getPropValues().getMySqlDAOMANAGER_db_server());
            System.out.println(properties.getPropValues().getMySqlDAOMANAGER_db_user());
        } catch (IOException ex) {
            Logger.getLogger(test_para_lanzar_metodos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        System.out.println(System.getProperty("user.dir"));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            // TODO add your handling code here:
            Rpt_Patients patients = new Rpt_Patients();
            patients.CallRPTListPatient();
        } catch (IOException ex) {
            Logger.getLogger(test_para_lanzar_metodos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void rbx_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbx_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbx_8ActionPerformed

    private void rbx_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbx_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbx_2ActionPerformed

    private void rbx_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbx_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbx_1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test_para_lanzar_metodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test_para_lanzar_metodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test_para_lanzar_metodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test_para_lanzar_metodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test_para_lanzar_metodos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private rojeru_san.componentes.RSDateChooser rSDateChooser2;
    private RSMaterialComponent.RSRadioButtonMaterial rSRadioButtonMaterial29;
    private RSMaterialComponent.RSRadioButtonMaterial rSRadioButtonMaterial30;
    private RSMaterialComponent.RSRadioButtonMaterial rSRadioButtonMaterial31;
    private RSMaterialComponent.RSRadioButtonMaterial rSRadioButtonMaterial32;
    private RSMaterialComponent.RSRadioButtonMaterial rSRadioButtonMaterial33;
    private RSMaterialComponent.RSRadioButtonMaterial rSRadioButtonMaterial34;
    private RSMaterialComponent.RSRadioButtonMaterial rSRadioButtonMaterial35;
    private RSMaterialComponent.RSRadioButtonMaterial rSRadioButtonMaterial36;
    private RSMaterialComponent.RSRadioButtonMaterial rSRadioButtonMaterial37;
    private RSMaterialComponent.RSRadioButtonMaterial rSRadioButtonMaterial38;
    private RSMaterialComponent.RSRadioButtonMaterial rSRadioButtonMaterial39;
    private RSMaterialComponent.RSRadioButtonMaterial rSRadioButtonMaterial41;
    private RSMaterialComponent.RSRadioButtonMaterial rSRadioButtonMaterial42;
    private RSMaterialComponent.RSRadioButtonMaterial rSRadioButtonMaterial43;
    private RSMaterialComponent.RSRadioButtonMaterial rbx_1;
    private RSMaterialComponent.RSRadioButtonMaterial rbx_10;
    private RSMaterialComponent.RSRadioButtonMaterial rbx_11;
    private RSMaterialComponent.RSRadioButtonMaterial rbx_12;
    private RSMaterialComponent.RSRadioButtonMaterial rbx_13;
    private RSMaterialComponent.RSRadioButtonMaterial rbx_14;
    private RSMaterialComponent.RSRadioButtonMaterial rbx_2;
    private RSMaterialComponent.RSRadioButtonMaterial rbx_3;
    private RSMaterialComponent.RSRadioButtonMaterial rbx_4;
    private RSMaterialComponent.RSRadioButtonMaterial rbx_5;
    private RSMaterialComponent.RSRadioButtonMaterial rbx_6;
    private RSMaterialComponent.RSRadioButtonMaterial rbx_7;
    private RSMaterialComponent.RSRadioButtonMaterial rbx_8;
    private RSMaterialComponent.RSRadioButtonMaterial rbx_9;
    // End of variables declaration//GEN-END:variables

    private void generateBackUpMysql() {
         Calendar c = Calendar.getInstance();//creamos una instancia de la clase calendar de java
        //java.util.Date fecha = new Date();
        String DiaHoy = Integer.toString(c.get(Calendar.DATE));
        String MesHoy = Integer.toString(c.get(Calendar.MONTH)+1);
        String AnioHoy = Integer.toString(c.get(Calendar.YEAR));        
                
        
        JFileChooser RealizarBackupMySQL = new JFileChooser();
        int resp;
        resp=RealizarBackupMySQL.showSaveDialog(this);//JFileChooser de nombre RealizarBackupMySQL
        if (resp==JFileChooser.APPROVE_OPTION) {//Si el usuario presiona aceptar; se genera el Backup
            try{
                Runtime runtime = Runtime.getRuntime();
                File backupFile = new File(String.valueOf(RealizarBackupMySQL.getSelectedFile().toString())+" "+DiaHoy +"-"+MesHoy+"-"+AnioHoy+".sql");
                FileWriter fw = new FileWriter(backupFile);
             
                Process child = runtime.exec("C:\\xampp\\mysql\\bin\\mysqldump --routines --opt --password= --user=root --databases utp2020-dental-system-dev"); 

               // Process child = runtime.exec("C:\\wamp\\bin\\mariadb\\mariadb10.4.10\\bin\\mysqldump --routines --opt --password= --user=root --databases utp2020-dental-system-dev"); 
                InputStreamReader irs = new InputStreamReader(child.getInputStream());
                BufferedReader br = new BufferedReader(irs);
                String line;
                while( (line=br.readLine()) != null ) {
                    fw.write(line + "\n");
                }
                fw.close();
                irs.close();
                br.close();
                JOptionPane.showMessageDialog(null, "Archivo generado","Verificar",JOptionPane. INFORMATION_MESSAGE);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error no se genero el archivo por el siguiente motivo:"+e.getMessage(), "Verificar",JOptionPane.ERROR_MESSAGE);
            }            
        } else if (resp==JFileChooser.CANCEL_OPTION) {
            JOptionPane.showMessageDialog(null,"Ha sido cancelada la generacion del Backup");
        }
    }
    
    private void restoreBackUpMysql(){
        
        String dbName="utp2020-dental-system-dev"; 
        String dbUserName="root";
        String dbPassword= "";
        
        int resp;
        JFileChooser RealizarBackupMySQL = new JFileChooser();
        resp=RealizarBackupMySQL.showOpenDialog(this);//Muestra el cuadro con la opcion abrir
        if (resp==JFileChooser.APPROVE_OPTION) 
        {//Si el usuario presiona aceptar(Abrir); Backup
            try
            {
                String ubicacion= String.valueOf(RealizarBackupMySQL.getSelectedFile().toString().trim());                
        
                //en nombre almacenamos la ruta del fichero con extension sql que se desea restaurar...
                String nombre = ubicacion.toString().substring(ubicacion.lastIndexOf('/')+1);
                File fichero=new File(nombre);
//                System.out.println("Path: " + ubicacion + " -- File: " + nombre);
                String dd=fichero.getName();//aqui obtenermos el nombre del fichero con extension sql.
                
                String[] executeCmd = new String[]{"C:\\wamp\\bin\\mariadb\\mariadb10.4.10\\bin\\mysql", "--password=" + dbPassword, "--user=" + dbUserName,  dbName,"-e", "source "+nombre};
                Process runtimeProcess;

                try {

                    runtimeProcess = Runtime.getRuntime().exec(executeCmd);

                    int processComplete = runtimeProcess.waitFor();

                    if (processComplete == 0) 
                    {
                        JOptionPane.showMessageDialog(null,"Backup realizado satisfactoriamente");
                        JOptionPane.showMessageDialog(null,dd);
                    } 
                    else
                    {
                        JOptionPane.showMessageDialog(null,"No se pudo realizar el Backup");
                        JOptionPane.showMessageDialog(null,dd);
                    }
                } catch (Exception ex) {
                }
            }
            catch (Exception ex) 
            {
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Ha sido cancelada la actualizacion del Backup");            
        }
        
    
    }
}
